args:
    config-4:
        experiment: 4
        dataset_repoid: "papluca/language-identification"
        model_str: "FacebookAI/xlm-roberta-base"
        batch_size: 8
        num_epochs: 5
        starting_epoch: 0
        lr: 2e-6
        optimizer: "adam"
        embedding_dim: 768
        max_seq_len: 512
        dropout_prob: 0.1
        f1_metric_average: "weighted"
        weight_decay: 1e-5
        precision: "full"
        train_valid_step: False
        test_step: True
        classification_report:
            digits: 3
            output_dict: False
        num_labels: 20
        datadir: "data"
        preprocessed_datadir: "data/preprocessed"
        model_ckpt_dir: "output/models/experiment-4"
        results_dir: "output/results/experiment-4/"
        log_dir: "output/logs/experiment-4"
    preprocessing:
        dataset_repoid: "papluca/language-identification"
        repo_type: "dataset"
        preprocessed_datadir: "data/preprocessed"
        datadir: "data"
        label_column: "labels"
        log_dir: "output/logs/data-preprocessing"
        